---
- name: Install pycurl
  apt: pkg=python-pycurl state=latest update-cache=yes force=yes
  sudo: yes
  tags:
    - packages

- name: Add JRE ppa
  sudo: yes
  apt_repository: repo=ppa:webupd8team/java state=present
  tags:
    - packages

- name: Automatically accept the Oracle License
  sudo: yes
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  tags:
    - packages

- name: Install JDK
  apt: pkg=oracle-java8-installer state=latest update-cache=yes force=yes
  sudo: yes
  tags:
    - packages